name: shopflow

services:

  postgres:
    image: postgres:15-alpine
    container_name: shopflow-postgres
    environment:
      POSTGRES_PASSWORD: shopflow123 # superuser password
      POSTGRES_USER: shopflow # creates this user automatically
      POSTGRES_DB: shopflow_users # creates this DB automatically
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shopflow -d shopflow_users" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s # give postgres time to init on first run
    networks:
      - shopflow-net

  user-service:
    build:
      context: ./services/user-service # Dockerfile location
      target: runner # stop at the "runner" stage (not builder)
    container_name: shopflow-user
    environment:
      PORT: 3001
      DB_HOST: postgres # ← SERVICE NAME, not localhost! Docker DNS resolves this
      DB_PORT: 5432
      DB_NAME: shopflow_users
      DB_USER: shopflow
      DB_PASSWORD: shopflow123
      JWT_SECRET: shopflow-dev-secret-change-in-prod
    ports:
      - "3001:3001" # expose to host so you can curl it directly
    depends_on:
      postgres:
        condition: service_healthy # only start AFTER postgres healthcheck passes
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3001/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shopflow-net
    restart: unless-stopped

  product-service:
    build:
      context: ./services/product-service
      target: runner
    container_name: shopflow-product
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shopflow_products
      DB_USER: shopflow
      DB_PASSWORD: shopflow123
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3002/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shopflow-net
    restart: unless-stopped

  order-service:
    build:
      context: ./services/order-service
      target: runner
    container_name: shopflow-order
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shopflow_orders
      DB_USER: shopflow
      DB_PASSWORD: shopflow123
      PRODUCT_SERVICE_URL: http://product-service:3002
      NOTIFICATION_SERVICE_URL: http://notification-service:3004
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
      product-service:
        condition: service_healthy # needs product-service to validate stock
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3003/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shopflow-net
    restart: unless-stopped

  notification-service:
    build:
      context: ./services/notification-service
      target: runner
    container_name: shopflow-notification
    environment:
      PORT: 3004
    ports:
      - "3004:3004"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3004/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shopflow-net
    restart: unless-stopped

  gateway:
    build:
      context: ./services/gateway
      target: runner
    container_name: shopflow-gateway
    environment:
      PORT: 3000
      USER_SERVICE_URL: http://user-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
      ORDER_SERVICE_URL: http://order-service:3003
      NOTIFICATION_SERVICE_URL: http://notification-service:3004
    ports:
      - "3000:3000" # THE only port exposed to your browser/curl
    depends_on:
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    networks:
      - shopflow-net
    restart: unless-stopped

networks:
  shopflow-net:
    driver: bridge # standard Docker network (uses Linux bridge + iptables)

volumes:
  postgres_data:
