apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow
type: Opaque
data:
  DB_PASSWORD: c2hvcGZsb3cxMjM=

  DB_USER: c2hvcGZsb3c=

  JWT_SECRET: c2hvcGZsb3ctazhzLXNlY3JldC1jaGFuZ2UtaW4tcHJvZA==

  POSTGRES_PASSWORD: c2hvcGZsb3cxMjM=
